name: notes
description: Notes app

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider:
  flutter_quill:
  hive:
  hive_flutter:
  flutter_slidable:
  flutter_launcher_icons:
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.2.1
  pinput: ^3.0.1
  firebase_core: ^2.17.0
  fluttertoast: ^8.2.2 

flutter_icons:
  image_path: "icon/icon-note.png" 
  android: true
  ios: true


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
